<script type="ts">
    import {createEventDispatcher} from 'svelte';
    import {
        Modal, Form, FormGroup, TextInput, TextArea, Button, Grid, Row, Column, CodeSnippet,
        InlineNotification, Tabs, Tab, TabContent, Select, SelectItem, NumberInput, Checkbox
    } from "carbon-components-svelte";
    import Save from "carbon-icons-svelte/lib/Save.svelte";
    import Add from "carbon-icons-svelte/lib/Add.svelte";
    import {v4 as uuid} from 'uuid';
    import GymVisualization from "./GymVisualization.svelte";

    const dispatch = createEventDispatcher();

    // props
    export let api;
    export let gyms;
    export let gym;

    let visualizationError;
    let initVisualization;
    let code;
    $: if (gym) {
        code = "# Environment '" + gym.name + "' generated by AutoRL X on " + gym.created_on.toLocaleDateString() + "\n";
        code += "# --------------------------------------------------------------------\n";
        code += "# Parameters:\n";
        for (let param of gym.params) {
            code += "# " + param.name + " = %" + param.name.toUpperCase() + "  # " + param.description + "\n";
        }
        code += "# --------------------------------------------------------------------\n";
        code += "from ARLO.environment import BaseEnvironment\nfrom mushroom_rl.utils.spaces import Box, Discrete\n";
        for (let module of gym.modules) {
            code += (module.type === "module" ? "import " : "from ") + module.module + (module.type === "submodules" ? (" import " + module.submodules) : module.submodules.length ? (" as " + module.submodules) : "") + "\n";
        }
        code += "\n\n"
        code += "class AutoRLXEnv(BaseEnvironment):\n";
        code += `    def __init__(self, obj_name="${gym.name}", seeder=2, log_mode='console', checkpoint_log_path=None, verbosity=3, n_jobs=1, job_type='process'):
        super().__init__(obj_name=obj_name, seeder=seeder, log_mode=log_mode, checkpoint_log_path=checkpoint_log_path, verbosity=verbosity, n_jobs=n_jobs, job_type=job_type)\n`;
        code += `        self.gamma = %GAMMA\n`;
        code += `        self.horizon = %HORIZON\n`;
        if (gym.spaces.observation.type === "discrete") {
            code += `        self.observation_space = Discrete(${gym.spaces.observation.size})\n\n`;
        } else {
            code += `        self.observation_space = Box(
            low=np.array(${gym.spaces.observation.low}),
            high=np.array(${gym.spaces.observation.high}),
            shape=(${gym.spaces.observation.size},)\n        )\n`;
        }
        if (gym.spaces.action.type === "discrete") {
            code += `        self.action_space = Discrete(${gym.spaces.action.size})\n\n`;
        } else {
            code += `        self.action_space = Box(
            low=np.array(${gym.spaces.action.low}),
            high=np.array(${gym.spaces.action.high}),
            shape=(${gym.spaces.action.size},)
        )\n\n`;
        }
        code += "    def reset(self, initial_state=None):";
        code += `${gym.reset.split("\n").map(line => "\n        " + line).join("")}`;
        code += "\n\n    def step(self, action):";
        if (gym.spaces.action.type === "discrete") {
            code += `\n        if isinstance(action, np.ndarray) and action.size > 1:\n            action = np.argmax(action)\n        elif isinstance(action, np.ndarray) and action.size == 1:\n            action = action.item()  # convert size-1 array to scalar`;
        }
        code += `${gym.step.split("\n").map(line => "\n        " + line).join("")}`;
        code += "\n\n    def render(self):\n        pass\n\n";
        code += `${gym.custom.split("\n").map(line => "\n    " + line).join("")}`;
        code += "\n"
        gym.code = code;
    }
</script>

<Modal
        open={gym !== null}
        modalHeading="Edit gym"
        primaryButtonText="Save gym"
        primaryButtonIcon={Save}
        primaryButtonDisabled={gym?.name?.length === 0 || gym?.code?.length === 0}
        secondaryButtonText="Cancel"
        selectorPrimaryFocus="#gym-name"
        hasForm
        preventCloseOnClickOutside
        shouldSubmitOnEnter={false}
        size="lg"
        class="gym-editor"
        on:click:button--secondary={() => (gym = null)}
        on:open
        on:close
        on:submit={()=>{
            gym.created_on = new Date();
            api.pushGym(gym).then(() => {
                gyms.push(gym);
                gym = null;
                gyms = gyms;
                dispatch('save');
            });
        }}
>
    {#if gym && gym.spaces}
        <Form on:submit>
            <Tabs autoWidth type="container">
                <Tab
                        label="General"
                        secondaryLabel="Manage gym metadata and parameters."
                        on:click={() => {
                          initVisualization = false;
                        }}
                />
                <Tab
                        label="Implementation (Python)"
                        secondaryLabel="Implement your gym."
                        on:click={() => {
                          initVisualization = false;
                        }}
                />
                <Tab
                        label="Visualization (TypeScript)"
                        secondaryLabel="Visualize your gym."
                        on:click={() => {
                            setTimeout(()=> {
                                initVisualization = true;
                            }, 1000);
                        }}
                />
                <Tab
                        label="Review"
                        secondaryLabel="View the fully rendered gym."
                        on:click={() => {
                          initVisualization = false;
                        }}
                />
                <svelte:fragment slot="content">
                    <TabContent>
                        <FormGroup>
                            <TextInput
                                    id="gym-name"
                                    labelText="Gym name"
                                    placeholder="Enter name..."
                                    bind:value={gym.name}
                                    on:change={() => {
                            gym["name"] = gym["name"].trim();
                        }}
                            />
                        </FormGroup>
                        <FormGroup legendText="Parameters">
                            <InlineNotification
                                    style="margin-top: 0px;"
                                    lowContrast
                                    kind="info"
                                    subtitle="Parameterize your gym to more easily try different variations of your implementation without losing track across runs later."
                            />
                            <Grid noGutter fullWidth>
                                {#each gym.params as param, i}
                                    <Row style="margin-bottom: 12px;">
                                        <Column>
                                            <TextInput
                                                    hideLabel
                                                    class="code"
                                                    placeHolder="Set parameter name..."
                                                    size="sm" bind:value={param["name"]} labelText="Name"
                                                    on:keyup={() => {
                                                        param["name"] = param["name"].replace(/^[\W\d]+/, "").replace(/[^a-zA-Z0-9_\s]/g, "");
                                                    }}
                                                    on:change={() => {
                                                        param["name"] = param["name"].trim();
                                                    }}
                                                    helperText={param["name"] ? "Reference with '%" + param["name"].replace(" ", "_").toUpperCase() +"' in code." : ""}
                                                    disabled={["gamma", "horizon"].includes(param.name)}
                                                    light={["gamma", "horizon"].includes(param.name)}
                                            />
                                        </Column>
                                        <Column>
                                            <TextInput
                                                    hideLabel
                                                    placeHolder="Enter parameter description..."
                                                    size="sm" bind:value={param["description"]}
                                                    labelText="Description"
                                                    disabled={["gamma", "horizon"].includes(param.name)}
                                                    light={["gamma", "horizon"].includes(param.name)}
                                            />
                                        </Column>
                                        <Column style="max-width: 150px;">
                                            <Select size="sm" hideLabel bind:selected={param["type"]}
                                                    disabled={["gamma", "horizon"].includes(param.name)}
                                                    light={["gamma", "horizon"].includes(param.name)}
                                            >
                                                <SelectItem value="str" text="String"/>
                                                <SelectItem value="int" text="Int"/>
                                                <SelectItem value="float" text="Float"/>
                                                <SelectItem value="bool" text="Boolean"/>
                                            </Select>
                                        </Column>
                                        <Column>
                                            {#if param["type"] === "str"}
                                                <TextInput
                                                        hideLabel
                                                        class="code"
                                                        placeHolder="Default value"
                                                        size="sm" bind:value={param["default"]}
                                                        labelText="Default value"
                                                />
                                            {:else if param["type"] === "int"}
                                                <NumberInput
                                                        placeHolder="Default value"
                                                        size="sm" bind:value={param["default"]}
                                                        labelText="Default value"
                                                        allowEmpty
                                                />
                                            {:else if param["type"] === "float"}
                                                <NumberInput
                                                        placeHolder="Default value"
                                                        size="sm" bind:value={param["default"]}
                                                        labelText="Default value"
                                                        allowEmpty
                                                        step={0.1}
                                                />
                                            {:else if param["type"] === "bool"}
                                                <Checkbox
                                                        labelText="Default value"
                                                        bind:checked={param["default"]}
                                                        on:check={()=>{
                                                            if(param["default"] === 0) {
                                                                param["default"] = null;
                                                            }
                                                        }}
                                                />
                                            {/if}
                                        </Column>
                                        <Column>
                                            <Button
                                                    kind="danger-ghost"
                                                    size="small"
                                                    on:click={() => {
                                                        gym.params.splice(i, 1);
                                                        gym = gym;
                                                    }}
                                                    disabled={["gamma", "horizon"].includes(param.name)}
                                            >
                                                Delete parameter
                                            </Button>
                                        </Column>
                                    </Row>
                                {/each}
                                <Row>
                                    <Column>
                                        <Button
                                                icon={Add}
                                                size="small"
                                                on:click={() => {
                                                    gym.params.push({
                                                        id: uuid(),
                                                        gym_id: gym.id,
                                                        name: "",
                                                        description: "",
                                                        type: "string",
                                                        default: null,
                                                        created_on: new Date()
                                                    });
                                                    gym = gym;
                                                }}
                                        >
                                            Add parameter
                                        </Button>
                                    </Column>
                                </Row>
                            </Grid>
                        </FormGroup>
                        <FormGroup legendText="Modules">
                            <InlineNotification
                                    style="margin-top: 0px;"
                                    lowContrast
                                    kind="info"
                                    subtitle="Specify module imports required by your gym implementation."
                            />
                            <Grid noGutter fullWidth>
                                {#each gym.modules as module, i}
                                    <Row style="margin-bottom: 12px;">
                                        <Column>
                                            <Select size="sm" hideLabel bind:selected={module.type}>
                                                <SelectItem value="module" text="import"/>
                                                <SelectItem value="submodules" text="from"/>
                                            </Select>
                                        </Column>
                                        <Column>
                                            <TextInput
                                                    size="sm"
                                                    placeHolder="Enter module name..."
                                                    class="code"
                                                    bind:value={module.module}
                                            />
                                        </Column>
                                        <Column>
                                            <Select size="sm" hideLabel>
                                                {#if module.type === "submodules"}
                                                    <SelectItem value="import" text="import"/>
                                                {:else}
                                                    <SelectItem value="as" text="as"/>
                                                {/if}
                                            </Select>
                                        </Column>
                                        <Column>
                                            <TextInput
                                                    size="sm"
                                                    class="code"
                                                    placeHolder={module.type === "submodules" ? "Enter submodules..." : module.module}
                                                    bind:value={module.submodules}
                                            />
                                        </Column>
                                        <Column>
                                            <Button kind="danger-ghost" size="small"
                                                    on:click={() => {
                                                        gym.modules.splice(i, 1);
                                                        gym = gym;
                                                    }}
                                            >Delete module
                                            </Button>
                                        </Column>
                                    </Row>
                                {/each}
                                <Row>
                                    <Column>
                                        <Button
                                                icon={Add}
                                                size="small"
                                                on:click={() => {
                                                    gym.modules.push({
                                                        id: uuid(),
                                                        gym_id: gym.id,
                                                        type: "module",
                                                        module: "my_module",
                                                        submodules: "",
                                                    });
                                                    gym = gym;
                                                }}
                                        >
                                            Add module
                                        </Button>
                                    </Column>
                                </Row>
                            </Grid>
                        </FormGroup>
                    </TabContent>
                    <TabContent class="no-legend-margin-bottom">
                        <FormGroup>
                            <Grid noGutter fullWidth>
                                <Row>
                                    <Column>
                                        <Select id="gym-id" labelText="Observation space"
                                                bind:selected={gym.spaces.observation.type}>
                                            <SelectItem value="box" text="Box"/>
                                            <SelectItem value="discrete" text="Discrete"/>
                                        </Select>
                                    </Column>
                                    <Column>
                                        <NumberInput min={0}
                                                     label={gym.spaces.observation.type === "box" ? "Length" : "Size"}
                                                     bind:value={gym.spaces.observation.size}/>
                                    </Column>

                                    <Column>
                                        {#if gym.spaces.observation.type === "box"}
                                            <TextInput class="code" labelText="Low"
                                                       bind:value={gym.spaces.observation.low}/>
                                        {/if}
                                    </Column>
                                    <Column>
                                        {#if gym.spaces.observation.type === "box"}
                                            <TextInput class="code" labelText="High"
                                                       bind:value={gym.spaces.observation.high}/>
                                        {/if}
                                    </Column>

                                </Row>
                            </Grid>
                        </FormGroup>
                        <FormGroup>
                            <Grid noGutter fullWidth>
                                <Row>
                                    <Column>
                                        <Select labelText="Action space" bind:selected={gym.spaces.action.type}>
                                            <SelectItem value="box" text="Box"/>
                                            <SelectItem value="discrete" text="Discrete"/>
                                        </Select>
                                    </Column>
                                    <Column>
                                        <NumberInput min={0}
                                                     label={gym.spaces.action.type === "box" ? "Length" : "Size"}
                                                     bind:value={gym.spaces.action.size}/>
                                    </Column>
                                    <Column>
                                        {#if gym.spaces.action.type === "box"}
                                            <TextInput class="code" labelText="Low" bind:value={gym.spaces.action.low}/>
                                        {/if}
                                    </Column>
                                    <Column>
                                        {#if gym.spaces.action.type === "box"}
                                            <TextInput class="code" labelText="High"
                                                       bind:value={gym.spaces.action.high}/>
                                        {/if}
                                    </Column>
                                </Row>
                            </Grid>
                        </FormGroup>
                        <FormGroup legendText="Initialization">
                            <TextArea
                                    value={`def reset(self, initial_state=None):`}
                                    style="padding-left: 15px; margin: 0px; margin-top: 6px; resize: none;"
                                    rows={1}
                                    disabled
                                    light
                                    class="code"
                            />
                            <TextArea
                                    style="padding-left: 50px; resize: none;"
                                    placeholder={`# e.g.\nself.gamma = %GAMMA  # if 'gamma' defined as parameter.\nself.horizon = 100\nself.state = [0] * ${gym.spaces.observation.size}\nreturn self.state`}
                                    bind:value={gym.reset}
                                    rows={Math.max(5, gym.reset?.split("\n").length)}
                                    helperText="This function needs to return state (array of numbers)."
                                    class="code"
                            />
                        </FormGroup>
                        <FormGroup legendText="Step function">
                            <TextArea
                                    value={`def step(self, action):`}
                                    style="padding-left: 15px; margin: 0px; margin-top: 6px; resize: none;"
                                    rows={1}
                                    light
                                    disabled
                                    class="code"
                            />
                            <TextArea
                                    style="padding-left: 50px; resize: none;"
                                    placeholder={`# e.g.\nself.state[action] += 1\nreward = max(self.state)\ndone=max(self.state) > 10\nreturn self.state, reward, done, {}`}
                                    bind:value={gym.step}
                                    rows={Math.max(5, gym.step?.split("\n").length)}
                                    helperText="This function needs to return state (array of numbers), reward (number), done (boolean) and an optional info (dictionary)."
                                    class="code"
                            />
                        </FormGroup>
                        <FormGroup legendText="Custom functions">
                            <TextArea
                                    style="margin-top: 6px; resize: none;"
                                    placeholder={`# e.g.\ndef some_utility_function(self, b):\n    self.a += b`}
                                    bind:value={gym.custom}
                                    rows={Math.max(3, gym.custom?.split("\n").length)}
                                    helperText="Space for additional custom helper functions."
                                    class="code"
                            />
                        </FormGroup>
                    </TabContent>
                    <TabContent>
                        <Grid noGutter fullWidth>
                            <Row>
                                <Column sm={2}>
                                    <TextArea
                                            value={`visualize(scene, camera, action, state, score) => {`}
                                            style="padding-left: 30px; margin: 0px; resize: none;"
                                            rows={1}
                                            class="code"
                                            disabled
                                            light
                                    />
                                    <TextArea
                                            style="padding-left: 40px; resize: none;"
                                            placeholder={`# e.g.\nconst geometry = new THREE.BoxGeometry(1, 1, 1);\nconst material = new THREE.MeshBasicMaterial({color: 0x00ff00});\nconst cube = new THREE.Mesh(geometry, material);\nscene.add(cube);`}
                                            bind:value={gym.visualization}
                                            rows={Math.max(6, gym.visualization?.split("\n").length)}
                                            helperText="Visualize state, action or score using Three.js."
                                            invalid={visualizationError}
                                            invalidText={visualizationError}
                                            class="code"
                                    />
                                </Column>
                                <Column sm={2}>
                                    <GymVisualization
                                            gym={gym} bind:visualizationError
                                            api={api}
                                            bind:initialize={initVisualization}
                                    />
                                </Column>
                            </Row>
                        </Grid>
                    </TabContent>
                    <TabContent>
                        <CodeSnippet expanded type="multi" code={gym.code} wrapText style="max-width: 100%;"/>
                    </TabContent>
                </svelte:fragment>
            </Tabs>
        </Form>
    {/if}
</Modal>